/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.KhachHangDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author tranc
 */
public class DangKyTheThanhVien extends javax.swing.JFrame {

    /**
     * Creates new form DangKyTheThanhVien
     */
    public DangKyTheThanhVien() {
        initComponents();
        setLocationRelativeTo(null);
        txtSoThe.setEnabled(false);
        txtSoThe.setText((" "+(Integer.parseInt(KhachHangDAO.LayMaThanhVien())+1)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbRegisterBY = new javax.swing.JLabel();
        jlbRegisterPW = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtSoThe = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jlbRegister = new javax.swing.JLabel();
        jlbRegisterN = new javax.swing.JLabel();
        jlbRegisterEM = new javax.swing.JLabel();
        jlbRegisterPO = new javax.swing.JLabel();
        jlbRegisterAd = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtBirthYear = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jlbRegisterBY1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        sprSoDiem = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbRegisterBY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterBY.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterBY.setText("Số Điện Thoại:");
        getContentPane().add(jlbRegisterBY, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 120, 30));

        jlbRegisterPW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterPW.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterPW.setText("Số Thẻ :");
        getContentPane().add(jlbRegisterPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 100, 30));

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 200, 30));

        txtSoThe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSoThe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoTheActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoThe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 200, 30));

        btnRegister.setBackground(new java.awt.Color(153, 153, 255));
        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-avatar.png"))); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jlbRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbRegister.setForeground(new java.awt.Color(204, 204, 255));
        jlbRegister.setText("ĐĂNG KÝ THẺ THÀNH VIÊN");
        getContentPane().add(jlbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 350, -1));

        jlbRegisterN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterN.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterN.setText("Anh/Chị :");
        getContentPane().add(jlbRegisterN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, 30));

        jlbRegisterEM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterEM.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterEM.setText("Email :");
        getContentPane().add(jlbRegisterEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, 30));

        jlbRegisterPO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterPO.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterPO.setText("Điểm Thưởng:");
        getContentPane().add(jlbRegisterPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 120, 30));

        jlbRegisterAd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterAd.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterAd.setText("Địa Chỉ:");
        getContentPane().add(jlbRegisterAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 30));

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 200, 30));

        txtBirthYear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtBirthYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 200, 30));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 200, 30));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, -1, -1));

        jlbRegisterBY1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterBY1.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterBY1.setText("Năm Sinh:");
        getContentPane().add(jlbRegisterBY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 110, 30));

        txtPhone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 200, 30));

        sprSoDiem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(sprSoDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 200, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/register.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
            String mathe = txtSoThe.getText();
            String name = txtName.getText();
            String email = txtEmail.getText();
            String diem = sprSoDiem.getValue().toString();
            String phone = txtPhone.getText();
            String namsinh = txtBirthYear.getText();
            String address = txtAddress.getText();
            
                if(KhachHangDAO.CreateKhachHang(name, email, address, namsinh, phone,diem)){
                    JOptionPane.showMessageDialog(null, "Thêm thành công thành viên "+name);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Thêm Thành Viên Thất Bại!");
                }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtSoTheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoTheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoTheActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DangKyTheThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DangKyTheThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DangKyTheThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DangKyTheThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DangKyTheThanhVien().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbRegister;
    private javax.swing.JLabel jlbRegisterAd;
    private javax.swing.JLabel jlbRegisterBY;
    private javax.swing.JLabel jlbRegisterBY1;
    private javax.swing.JLabel jlbRegisterEM;
    private javax.swing.JLabel jlbRegisterN;
    private javax.swing.JLabel jlbRegisterPO;
    private javax.swing.JLabel jlbRegisterPW;
    private javax.swing.JSpinner sprSoDiem;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthYear;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSoThe;
    // End of variables declaration//GEN-END:variables

}
