/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.NhanVienDAO;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author tranc
 */
public class DangKy extends javax.swing.JFrame {

    String imagePath;
    /**
     * Creates new form DangKy
     */
    public DangKy() {
        initComponents();
        setLocationRelativeTo(null);
        erro.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbRegisterBY = new javax.swing.JLabel();
        jlbRegisterPW = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPWRe = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jlbRegister = new javax.swing.JLabel();
        jlbRegisterUS = new javax.swing.JLabel();
        jlbRegisterN = new javax.swing.JLabel();
        jlbRegisterEM = new javax.swing.JLabel();
        jlbRegisterPO = new javax.swing.JLabel();
        jlbRegisterAd = new javax.swing.JLabel();
        txtUsernameRe = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtBirthYear = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jcboPosition = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jlbRegisterBY1 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        erro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jlbRegisterBY2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbRegisterBY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterBY.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterBY.setText("Avatar: ");
        getContentPane().add(jlbRegisterBY, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 110, 30));

        jlbRegisterPW.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterPW.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterPW.setText("Password :");
        getContentPane().add(jlbRegisterPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 100, 30));

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 200, 30));

        txtPWRe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtPWRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 200, 30));

        btnRegister.setBackground(new java.awt.Color(153, 153, 255));
        btnRegister.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jlbRegister.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jlbRegister.setForeground(new java.awt.Color(153, 0, 153));
        jlbRegister.setText("Create Employee");
        getContentPane().add(jlbRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 210, -1));

        jlbRegisterUS.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterUS.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterUS.setText("Username :");
        getContentPane().add(jlbRegisterUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 100, 30));

        jlbRegisterN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterN.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterN.setText("Name :");
        getContentPane().add(jlbRegisterN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 90, 30));

        jlbRegisterEM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterEM.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterEM.setText("Email :");
        getContentPane().add(jlbRegisterEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 90, 30));

        jlbRegisterPO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterPO.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterPO.setText("Position :");
        getContentPane().add(jlbRegisterPO, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 90, 30));

        jlbRegisterAd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterAd.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterAd.setText("Address :");
        getContentPane().add(jlbRegisterAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 90, 30));

        txtUsernameRe.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtUsernameRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 200, 30));

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 200, 30));

        txtBirthYear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtBirthYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 200, 30));

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 200, 30));

        jcboPosition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Manager" }));
        getContentPane().add(jcboPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 200, 30));

        btnBack.setBackground(new java.awt.Color(153, 153, 255));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        jlbRegisterBY1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterBY1.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterBY1.setText("BirthYear :");
        getContentPane().add(jlbRegisterBY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 110, 30));

        txtPhone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 200, 30));

        erro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        erro.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(erro, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 370, -1));

        jButton1.setText("Choose File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jlbRegisterBY2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbRegisterBY2.setForeground(new java.awt.Color(255, 255, 255));
        jlbRegisterBY2.setText("Phone :");
        getContentPane().add(jlbRegisterBY2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/nv.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/register.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        if(validateData()){    
            String userName = txtUsernameRe.getText();
            String passWord = txtPWRe.getText();
            String name = txtName.getText();
            String email = txtEmail.getText();
            String position = jcboPosition.getSelectedItem().toString();
            String phone = txtPhone.getText();
            String namsinh = txtBirthYear.getText();
            String address = txtAddress.getText();
            if(position.equals("Staff")){
                System.out.println(imagePath);
                if(NhanVienDAO.CreateStaff(userName, passWord, name, email, position, address, namsinh, phone,imagePath.trim())){
                    JOptionPane.showMessageDialog(null, "Thêm thành công nhân viên "+name);
                }
                else JOptionPane.showMessageDialog(null, "Thêm thất bại nhân viên "+name);
            }
            else{
                if(NhanVienDAO.CreateManager(userName, passWord, name, email, position, address, namsinh, phone,imagePath.trim())){
                    JOptionPane.showMessageDialog(null, "Thêm thành công nhân viên "+name);
                }
            }
          
        }
        
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String filePath = selectedFile.getAbsolutePath();
            String projectDirectory = "C:\\DoAnJava\\QL_CaPhe\\QL_CaPhe\\QL_CaPhe\\src\\Image\\";
            imagePath = filePath.substring(projectDirectory.length());
          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel erro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcboPosition;
    private javax.swing.JLabel jlbRegister;
    private javax.swing.JLabel jlbRegisterAd;
    private javax.swing.JLabel jlbRegisterBY;
    private javax.swing.JLabel jlbRegisterBY1;
    private javax.swing.JLabel jlbRegisterBY2;
    private javax.swing.JLabel jlbRegisterEM;
    private javax.swing.JLabel jlbRegisterN;
    private javax.swing.JLabel jlbRegisterPO;
    private javax.swing.JLabel jlbRegisterPW;
    private javax.swing.JLabel jlbRegisterUS;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBirthYear;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPWRe;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtUsernameRe;
    // End of variables declaration//GEN-END:variables
public boolean validateData(){
    
    String username = txtUsernameRe.getText();
    String name = txtName.getText();
    String email= txtEmail.getText();
    String birthYear = txtBirthYear.getText();
    String address = txtAddress.getText();
    String phone = txtPhone.getText();
    if(username.isEmpty()||name.isEmpty()||email.isEmpty()||birthYear.isEmpty()||address.isEmpty()){
        return false;
    }
    if(!NhanVienDAO.kiemTraUserName(username)){
        erro.setText("Username đã tồn tại");
        return false;
    }
    if(username.contains(" ")){
        erro.setText("Username không hợp lệ");
        return false;
    }
    if(birthYear.matches("^\\\\d+$")){
        erro.setText("Năm sinh không hợp lệ");
        return false;
    }
    if(!NhanVienDAO.kiemTraEmail(email)){
        erro.setText("Email đã tồn tại");
        return false;
    }
    return true;
}
}
