/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.HoaDonDAO;
import DAO.KhachHangDAO;
import DAO.NhanVienDAO;
import DAO.SQLServerProvider;
import DAO.SanPhamDAO;
import POJO.KhachHang;
import java.awt.Font;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author tranc
 */
public final class frmBanHang extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form frmBanHang
     */
    List<List<String>> dsSanPhamGiaoDich = new ArrayList<>();
    private List<String> data;
    private List<String> dataKhachHang;
    public frmBanHang() {
        initComponents();
        load();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNgayLapHoaDon2 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        rdoKhachTV = new javax.swing.JRadioButton();
        rdoKhachLe = new javax.swing.JRadioButton();
        jpnelKhachHangThanhVien = new javax.swing.JPanel();
        jlbThongTin = new javax.swing.JLabel();
        txtDiemTV = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cboKhachHang = new javax.swing.JComboBox<>();
        rdoTichDiem = new javax.swing.JRadioButton();
        rdoDoiDiem = new javax.swing.JRadioButton();
        jlbThongTin1 = new javax.swing.JLabel();
        txtKhach = new javax.swing.JTextField();
        jlbThongTin2 = new javax.swing.JLabel();
        txtTenKhach = new javax.swing.JTextField();
        btnDangKyThanhVien = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListBillDetails = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TXTSAP = new javax.swing.JTextField();
        cboSanPham = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sprSoLuong = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cbogiamgia = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        txtNgayLapHoaDon = new javax.swing.JPanel();
        txtMaHoaDon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        txtTenNguoiLap = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        btnPrint = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1334, 729));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Giao Diện Bán Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 70));

        txtNgayLapHoaDon2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        txtNgayLapHoaDon2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayLapHoaDon2.setOpaque(false);

        buttonGroup2.add(rdoKhachTV);
        rdoKhachTV.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rdoKhachTV.setText("Khách Thành Viên");
        rdoKhachTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhachTVActionPerformed(evt);
            }
        });

        buttonGroup2.add(rdoKhachLe);
        rdoKhachLe.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rdoKhachLe.setText("Khách Thường");
        rdoKhachLe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhachLeActionPerformed(evt);
            }
        });

        jpnelKhachHangThanhVien.setOpaque(false);

        jlbThongTin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbThongTin.setText("Điểm Thành Viên:");

        txtDiemTV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtDiemTV.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Chọn Khách:");

        cboKhachHang.setEditable(true);
        cboKhachHang.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cboKhachHang.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cboKhachHangInputMethodTextChanged(evt);
            }
        });
        cboKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhachHangActionPerformed(evt);
            }
        });
        cboKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboKhachHangKeyReleased(evt);
            }
        });

        buttonGroup1.add(rdoTichDiem);
        rdoTichDiem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rdoTichDiem.setText("Tích Điểm");
        rdoTichDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTichDiemActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDoiDiem);
        rdoDoiDiem.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        rdoDoiDiem.setText("Đổi Điểm");
        rdoDoiDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDoiDiemActionPerformed(evt);
            }
        });

        jlbThongTin1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbThongTin1.setText("Thông Tin Khách:");

        txtKhach.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtKhach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKhachKeyReleased(evt);
            }
        });

        jlbThongTin2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbThongTin2.setText("Tên Khách Hàng: ");

        txtTenKhach.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTenKhach.setEnabled(false);

        btnDangKyThanhVien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDangKyThanhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user-avatar.png"))); // NOI18N
        btnDangKyThanhVien.setText("Đăng Ký Thành Viên");
        btnDangKyThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyThanhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnelKhachHangThanhVienLayout = new javax.swing.GroupLayout(jpnelKhachHangThanhVien);
        jpnelKhachHangThanhVien.setLayout(jpnelKhachHangThanhVienLayout);
        jpnelKhachHangThanhVienLayout.setHorizontalGroup(
            jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                        .addComponent(jlbThongTin2)
                        .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(rdoTichDiem)
                                .addGap(94, 94, 94)
                                .addComponent(rdoDoiDiem)
                                .addContainerGap(103, Short.MAX_VALUE))
                            .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKhach)
                                    .addComponent(txtDiemTV))
                                .addContainerGap())))
                    .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                        .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(60, 60, 60)
                                .addComponent(cboKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDangKyThanhVien)
                                    .addComponent(jlbThongTin))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbThongTin1)
                    .addContainerGap(460, Short.MAX_VALUE)))
            .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnelKhachHangThanhVienLayout.createSequentialGroup()
                    .addContainerGap(170, Short.MAX_VALUE)
                    .addComponent(txtKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jpnelKhachHangThanhVienLayout.setVerticalGroup(
            jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cboKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbThongTin2)
                    .addComponent(txtTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiemTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTichDiem)
                    .addComponent(rdoDoiDiem)
                    .addComponent(btnDangKyThanhVien))
                .addContainerGap())
            .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(jlbThongTin1)
                    .addContainerGap(133, Short.MAX_VALUE)))
            .addGroup(jpnelKhachHangThanhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnelKhachHangThanhVienLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(txtKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout txtNgayLapHoaDon2Layout = new javax.swing.GroupLayout(txtNgayLapHoaDon2);
        txtNgayLapHoaDon2.setLayout(txtNgayLapHoaDon2Layout);
        txtNgayLapHoaDon2Layout.setHorizontalGroup(
            txtNgayLapHoaDon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNgayLapHoaDon2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(txtNgayLapHoaDon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtNgayLapHoaDon2Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(txtNgayLapHoaDon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6)
                            .addGroup(txtNgayLapHoaDon2Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(jLabel17)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(486, 486, 486))
                    .addGroup(txtNgayLapHoaDon2Layout.createSequentialGroup()
                        .addGroup(txtNgayLapHoaDon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtNgayLapHoaDon2Layout.createSequentialGroup()
                                .addComponent(rdoKhachTV)
                                .addGap(18, 18, 18)
                                .addComponent(rdoKhachLe))
                            .addComponent(jpnelKhachHangThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        txtNgayLapHoaDon2Layout.setVerticalGroup(
            txtNgayLapHoaDon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNgayLapHoaDon2Layout.createSequentialGroup()
                .addGroup(txtNgayLapHoaDon2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoKhachTV)
                    .addComponent(rdoKhachLe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnelKhachHangThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(txtNgayLapHoaDon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 670, 290));

        jPanel4.setOpaque(false);

        jtbListBillDetails.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtbListBillDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbListBillDetails.setRowHeight(30);
        jtbListBillDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbListBillDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbListBillDetails);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 670, 220));

        jPanel5.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Tên Sản Phẩm: ");

        TXTSAP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        TXTSAP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXTSAPKeyReleased(evt);
            }
        });

        cboSanPham.setEditable(true);
        cboSanPham.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cboSanPham.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cboSanPhamInputMethodTextChanged(evt);
            }
        });
        cboSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cboSanPhamKeyReleased(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Số lượng");

        sprSoLuong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Chọn sản Phẩm");

        btnLamMoi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Giảm Giá");

        cbogiamgia.setEditable(true);
        cbogiamgia.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cbogiamgia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20", "25", "30", "35", "40", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95" }));
        cbogiamgia.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cbogiamgiaInputMethodTextChanged(evt);
            }
        });
        cbogiamgia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbogiamgiaKeyReleased(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/update.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel6))
                                    .addGap(52, 52, 52)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnThem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sprSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TXTSAP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboSanPham, javax.swing.GroupLayout.Alignment.LEADING, 0, 336, Short.MAX_VALUE))
                            .addComponent(cbogiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnXoa)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMoi))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sprSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbogiamgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi)
                    .addComponent(btnSua))
                .addGap(24, 24, 24))
        );

        txtNgayLapHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        txtNgayLapHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayLapHoaDon.setOpaque(false);

        txtMaHoaDon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtMaHoaDon.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Mã Hóa Đơn");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Ngày lập hóa đơn");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Tên người lập");

        txtTenNguoiLap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTenNguoiLap.setEnabled(false);
        txtTenNguoiLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNguoiLapActionPerformed(evt);
            }
        });

        txtNgayLap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNgayLap.setEnabled(false);

        javax.swing.GroupLayout txtNgayLapHoaDonLayout = new javax.swing.GroupLayout(txtNgayLapHoaDon);
        txtNgayLapHoaDon.setLayout(txtNgayLapHoaDonLayout);
        txtNgayLapHoaDonLayout.setHorizontalGroup(
            txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNgayLapHoaDonLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(45, 45, 45)
                .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4)
                    .addGroup(txtNgayLapHoaDonLayout.createSequentialGroup()
                        .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtNgayLapHoaDonLayout.createSequentialGroup()
                                .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNgayLap, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
        );
        txtNgayLapHoaDonLayout.setVerticalGroup(
            txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtNgayLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(txtNgayLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNgayLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, 560, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Tổng Tiền: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 110, 30));

        txtTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTongTien.setEnabled(false);
        getContentPane().add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 620, 288, 30));

        btnPrint.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/printer.png"))); // NOI18N
        btnPrint.setText("Xuất Hóa Đơn");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 610, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg.jpg"))); // NOI18N
        bg.setToolTipText("");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 0, 1310, 729));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSanPhamInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cboSanPhamInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cboSanPhamInputMethodTextChanged

    private void cboSanPhamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboSanPhamKeyReleased
     
    }//GEN-LAST:event_cboSanPhamKeyReleased

    private void TXTSAPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTSAPKeyReleased
   String userInput =TXTSAP.getText().trim(); 
   cboSanPham.removeAllItems(); 
   JComboBox<String> tempComboBox = new JComboBox<>();
    for (String item : data) {
        if (item.toLowerCase().contains(userInput.toLowerCase())) {
            tempComboBox.addItem(item);
        }
    }
 
    for (int i = 0; i < tempComboBox.getItemCount(); i++) {
        cboSanPham.addItem(tempComboBox.getItemAt(i));
    }
    cboSanPham.setPopupVisible(true); // Hiển thị danh sách gợi ý
    }//GEN-LAST:event_TXTSAPKeyReleased

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String selectedProductName = (String) cboSanPham.getSelectedItem();
        int quantity = (int) sprSoLuong.getValue();
        double discount  = Double.parseDouble(cbogiamgia.getSelectedItem().toString());
        double price = HoaDonDAO.getProductPriceByName(selectedProductName);
        
        double totalPrice = price * quantity;
        DefaultTableModel model = (DefaultTableModel) jtbListBillDetails.getModel();
        boolean chkNew = true;
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).toString().equals(selectedProductName)) {
                int currentQuantity = (int) model.getValueAt(i, 1);
                int count = currentQuantity + quantity;
                  if(count == 0)
                        model.removeRow(i);
                 if (count <= 0)
                        JOptionPane.showMessageDialog(null, "Vui lòng chọn một số lượng lớn hơn 0.");
                model.setValueAt(count, i, 1); 
                
                model.setValueAt((currentQuantity + quantity) * price - ((currentQuantity + quantity) * price)*(discount/100) , i, 4); 
                chkNew =false;
            }
      }
        if(chkNew){
          if(quantity <= 0) JOptionPane.showMessageDialog(null, "Vui lòng chọn một số lượng lớn hơn 0.");
           else{
                   model.addRow(new Object[]{selectedProductName, quantity, price,discount,totalPrice -  totalPrice*(discount/100)});
                }
        }
         // gợi ý
        Map<Integer, List<String>> billProductMap = new HashMap<>();
        String idSanPham = HoaDonDAO.getProductIDByName(cboSanPham.getSelectedItem().toString());
        billProductMap = HoaDonDAO.layDanhsacHoaDonPhoBienTuMa(idSanPham);
        for (Map.Entry<Integer, List<String>> entry : billProductMap.entrySet()) {
           List<String> itemset = new ArrayList<>();
           itemset = entry.getValue();
           dsSanPhamGiaoDich.add(itemset);
        }
         cboSanPham.removeAllItems();
         billProductMap.clear();
        double minSupport = 1; 
       List<List<String>> frequentItemsets = apriori(dsSanPhamGiaoDich, minSupport);
        Set<String> addedItems = new HashSet<>(); 
        for (List<String> itemset : frequentItemsets) {
            for(String item : itemset){
                if (!addedItems.contains(item)) { 
                    cboSanPham.addItem(item); 
                    addedItems.add(item); 
                }
            }
        }
        dsSanPhamGiaoDich.clear();
        tinhTongTien(model);
    }//GEN-LAST:event_btnThemActionPerformed
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRow = jtbListBillDetails.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) jtbListBillDetails.getModel();
        model.removeRow(selectedRow);
        tinhTongTien(model);
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTenNguoiLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNguoiLapActionPerformed

    }//GEN-LAST:event_txtTenNguoiLapActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtbListBillDetails.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedRow = jtbListBillDetails.getSelectedRow();
        System.out.println(selectedRow);
               if (selectedRow == -1) {
                   JOptionPane.showMessageDialog(null, "Vui lòng chọn một dòng để xóa.");
                   return;
               }
               
               DefaultTableModel model = (DefaultTableModel) jtbListBillDetails.getModel();
               model.setValueAt(cboSanPham.getSelectedItem().toString(), selectedRow, 0);
               double price = HoaDonDAO.getProductPriceByName(cboSanPham.getSelectedItem().toString());
               model.setValueAt((int)sprSoLuong.getValue(), selectedRow, 1);
                model.setValueAt(price, selectedRow, 2);
               model.setValueAt(cbogiamgia.getSelectedItem().toString(), selectedRow, 3);
               model.setValueAt( tinhGiamGia((int)sprSoLuong.getValue(), price, Double.parseDouble(cbogiamgia.getSelectedItem().toString())) , selectedRow,4); 
               tinhTongTien(model);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
       if(txtMaHoaDon.getText().isEmpty())return;
        if(jtbListBillDetails.getModel().getRowCount()<=0)return;
        KhachHangDAO.updateDiemThuong(cboKhachHang.getSelectedItem().toString(), txtDiemTV.getText());
        LocalDate today = LocalDate.now();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd");
         DefaultTableModel model = (DefaultTableModel) jtbListBillDetails.getModel();
         double discountBill =currentTongTien(model)*0.1;
         String tongTien = txtTongTien.getText();
        if(!HoaDonDAO.InsertHoaDon(String.valueOf(discountBill),tongTien, today.format(dateFormat),NhanVienDAO.TimMaNhanVienTuUserName(),cboKhachHang.getSelectedItem().toString() ))return;
        for (int i = 0; i < model.getRowCount(); i++) {
            HoaDonDAO.InsertChiTietHoaDon(txtMaHoaDon.getText()
                    , SanPhamDAO.layMaSanPhamTuTen(model.getValueAt(i, 0).toString())
                   , model.getValueAt(i, 1).toString(),model.getValueAt(i, 3).toString(),model.getValueAt(i, 4).toString());
       }
        xuatHoaDon();
        load();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void rdoKhachTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhachTVActionPerformed
        // TODO add your handling code here:
        dataKhachHang = KhachHangDAO.layDanhsachMaKH();
        rdoDoiDiem.setVisible(true);
        rdoTichDiem.setVisible(true);
        btnDangKyThanhVien.setVisible(false);
    }//GEN-LAST:event_rdoKhachTVActionPerformed

    private void rdoKhachLeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhachLeActionPerformed
        // TODO add your handling code here:
        rdoDoiDiem.setVisible(false);
        rdoTichDiem.setVisible(false);
        btnDangKyThanhVien.setVisible(true);
        cboKhachHang.setSelectedItem(0);
    }//GEN-LAST:event_rdoKhachLeActionPerformed

    private void cboKhachHangInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cboKhachHangInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhachHangInputMethodTextChanged

    private void cboKhachHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboKhachHangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cboKhachHangKeyReleased

    private void btnDangKyThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyThanhVienActionPerformed
        // TODO add your handling code here:
         DangKyTheThanhVien fDangKy = new DangKyTheThanhVien();
         fDangKy.setVisible(true);
    }//GEN-LAST:event_btnDangKyThanhVienActionPerformed

    private void cbogiamgiaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbogiamgiaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbogiamgiaInputMethodTextChanged

    private void cbogiamgiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbogiamgiaKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbogiamgiaKeyReleased

    private void jtbListBillDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListBillDetailsMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jtbListBillDetails.getModel();
        int row = jtbListBillDetails.getSelectedRow();
        if(row >=0){
            cboSanPham.setSelectedItem(jtbListBillDetails.getValueAt(row, 0));
            sprSoLuong.setValue(Integer.valueOf(jtbListBillDetails.getValueAt(row, 1).toString()));
            cbogiamgia.setSelectedItem(jtbListBillDetails.getValueAt(row, 3));
           
        }
    }//GEN-LAST:event_jtbListBillDetailsMouseClicked

    private void txtKhachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKhachKeyReleased
        // TODO add your handling code here:
        int userInput = 0;
        try {
            if(txtKhach.getText().trim().isEmpty())userInput = 0;
            else
             userInput = Integer.parseInt( txtKhach.getText().trim());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập số!");
        }
         for (String item : dataKhachHang) {
             if (Integer.parseInt(item) == userInput) {
                 cboKhachHang.setSelectedItem(String.valueOf(item));
             }
         }
    }//GEN-LAST:event_txtKhachKeyReleased

    private void cboKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhachHangActionPerformed
        // TODO add your handling code here:
        KhachHang kh = new KhachHang();
        kh = KhachHangDAO.TimKhachHangTuMaThe(cboKhachHang.getSelectedItem().toString());
        txtDiemTV.setText(String.valueOf(kh.getDiemThuong()));
        txtTenKhach.setText(kh.getName());
        if(kh.getDiemThuong() == 0)rdoDoiDiem.setEnabled(false);
        else rdoDoiDiem.setEnabled(true);
    }//GEN-LAST:event_cboKhachHangActionPerformed

    private void rdoDoiDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDoiDiemActionPerformed
        // TODO add your handling code here:
       DoiDiem();
    }//GEN-LAST:event_rdoDoiDiemActionPerformed

    private void rdoTichDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTichDiemActionPerformed
        // TODO add your handling code here:
       TichDiem();
    }//GEN-LAST:event_rdoTichDiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TXTSAP;
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnDangKyThanhVien;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboKhachHang;
    private javax.swing.JComboBox<String> cboSanPham;
    private javax.swing.JComboBox<String> cbogiamgia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel jlbThongTin;
    private javax.swing.JLabel jlbThongTin1;
    private javax.swing.JLabel jlbThongTin2;
    private javax.swing.JPanel jpnelKhachHangThanhVien;
    private javax.swing.JTable jtbListBillDetails;
    private javax.swing.JRadioButton rdoDoiDiem;
    private javax.swing.JRadioButton rdoKhachLe;
    private javax.swing.JRadioButton rdoKhachTV;
    private javax.swing.JRadioButton rdoTichDiem;
    private javax.swing.JSpinner sprSoLuong;
    private javax.swing.JTextField txtDiemTV;
    private javax.swing.JTextField txtKhach;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JPanel txtNgayLapHoaDon;
    private javax.swing.JPanel txtNgayLapHoaDon2;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTenNguoiLap;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
void load(){
        
        JTableHeader header = jtbListBillDetails.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16)); 
        dataKhachHang = KhachHangDAO.layDanhsachMaKH();
        addCombobox(cboKhachHang, dataKhachHang);
        rdoDoiDiem.setVisible(false);
        rdoTichDiem.setVisible(false);
        btnDangKyThanhVien.setVisible(true);
        LocalDate today = LocalDate.now();
        DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtNgayLap.setText(today.format(dateFormat));
        txtMaHoaDon.setText((Integer.parseInt(HoaDonDAO.LayMaHoaDon())+1)+" ");
        txtTenNguoiLap.setText(NhanVienDAO.TimNhanVienTuMaNhanVien().getName());
        cboKhachHang.setSelectedIndex(0);
        txtKhach.setText(" ");
        LoabFood();
}
private void LoabFood(){
    txtTongTien.setText(" ");
    TXTSAP.setText(" ");
    data = SanPhamDAO.layDanhsachTenSanPham();
    addCombobox(cboSanPham, data);
    DefaultTableModel defaultTableModel = (DefaultTableModel) jtbListBillDetails.getModel();
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        defaultTableModel.addColumn("Tên Sản Phẩm");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Đơn giá");
        defaultTableModel.addColumn("Giảm Giá (%)");
        defaultTableModel.addColumn("Thành tiền");
  sprSoLuong.setValue(0);
  cbogiamgia.setSelectedIndex(0);
}
private void addCombobox(JComboBox<String> com,List<String> data){
    for (String item : data) {
        com.addItem(item);
        }
}
private void tinhTongTien(DefaultTableModel model){
    double totalBill = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
                totalBill+=Double.parseDouble(model.getValueAt(i, 4).toString());
            }
      
        txtTongTien.setText(String.valueOf(totalBill));
        if(rdoTichDiem.isSelected()){
            TichDiem();
        }
        if(rdoDoiDiem.isSelected()){
            DoiDiem();
        }
 }
private double currentTongTien(DefaultTableModel model){
    double totalBill = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
                totalBill+=Double.parseDouble(model.getValueAt(i, 4).toString());
            }
        return totalBill;
}
 public void xuatHoaDon() {
    SQLServerProvider provider = new SQLServerProvider();
    provider.open();
    try {
        Hashtable<String, Object> map = new Hashtable<>();
        map.put("MaHoaDon", txtMaHoaDon.getText());
        JasperReport report = JasperCompileManager.compileReport("src/GUI/reportHoaDon.jrxml");
        JasperPrint p = JasperFillManager.fillReport(report, map, provider.connection);
        JasperViewer.viewReport(p, false);
    } catch (JRException ex) {
        Logger.getLogger(frmBanHang.class.getName()).log(Level.SEVERE, null, ex);
    }
}
 public double  tinhGiamGia(int soluong,double Price , double discount){
    return soluong*Price - soluong*Price*(discount/100);
}
 private void TichDiem(){
        DefaultTableModel model =(DefaultTableModel) jtbListBillDetails.getModel();
        double tonght = currentTongTien(model);
        double diem = KhachHangDAO.TimKhachHangTuMaThe(cboKhachHang.getSelectedItem().toString()).getDiemThuong()+tonght*0.05;

        txtDiemTV.setText(String.valueOf(diem));
        txtTongTien.setText(String.valueOf(tonght));
 }
 private void DoiDiem(){
     DefaultTableModel model =(DefaultTableModel) jtbListBillDetails.getModel();
        double tonght = currentTongTien(model);
        double tong;
        double diem =  KhachHangDAO.TimKhachHangTuMaThe(cboKhachHang.getSelectedItem().toString()).getDiemThuong()+tonght*0.05;
        if(diem >= tonght*0.1){
            diem = diem - tonght*0.1;
             tong = tonght*0.9;
        }
        else{
            tong = tonght - diem;
             diem = 0;
        }
        txtDiemTV.setText(String.valueOf(diem));
        txtTongTien.setText(String.valueOf(tong));
}
public static List<List<String>> apriori(List<List<String>> transactions, double minSupport) {
        List<List<String>> frequentItemsets = new ArrayList<>();
        Map<String, Integer> itemCount = new HashMap<>();
        for (List<String> transaction : transactions) {
            for (String item : transaction) {
                itemCount.put(item, itemCount.getOrDefault(item, 0) + 1);
            }
        }
        // Từ Tập đơn sản phẩm loại đi những sản phẩm dưới ngưỡng hỗ trợ
        List<List<String>> frequent1Itemsets = new ArrayList<>();
        for (Map.Entry<String, Integer> entry : itemCount.entrySet()) {
            if (entry.getValue() >= minSupport) {
                List<String> itemset = new ArrayList<>();
                itemset.add(entry.getKey());
                frequent1Itemsets.add(itemset);
            }
        }
        frequentItemsets = findFrequentItemsets(transactions,frequent1Itemsets,minSupport);
       
        return frequentItemsets;
    } 

public static  List<List<String>> findFrequentItemsets(List<List<String>> transactions, List<List<String>> frequent1Itemsets, double minSupport) {
    int k = 2;
    List<List<String>> frequentItemsets = new ArrayList<>();
    List<List<String>> candidateItemsets = frequent1Itemsets;
    Set<List<String>> countedItemsets = new HashSet<>();
    while (!candidateItemsets.isEmpty() && k <= transactions.size()) {
        Map<List<String>, Integer> candidateCount = new HashMap<>();
        for (List<String> transaction : transactions) {
            for (List<String> candidate : candidateItemsets) {
                if (transaction.containsAll(candidate)) {
                    if (!countedItemsets.contains(candidate)) {
                        candidateCount.put(candidate, candidateCount.getOrDefault(candidate, 0) + 1);
                        countedItemsets.add(candidate);
                    }
                }
            }
        }
        candidateItemsets = new ArrayList<>();
        for (Map.Entry<List<String>, Integer> entry : candidateCount.entrySet()) {
            List<String> itemset = entry.getKey();
            int count = entry.getValue();
            if (count >= minSupport) { // Kiểm tra xem tập hợp ứng viên có đạt đủ hỗ trợ không
                candidateItemsets.add(itemset); 
            }
        }
        countedItemsets.clear();
        frequentItemsets.addAll(candidateItemsets); // Thêm các tập hợp ứng viên mới vào danh sách các tập hợp phổ biến
        k++;
    }
    return frequentItemsets; // Trả về danh sách các tập hợp phổ biến
}

}
