/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.LoaiDAO;
import POJO.Loai;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Admin
 */
public class frmCategory extends javax.swing.JInternalFrame {
  ArrayList<Loai> dsLoai = LoaiDAO.layDanhsachLoai();
    /**
     * Creates new form frmCategory
     */
    public frmCategory() {
        initComponents();
        LoadForm(dsLoai);
        JTableHeader header = jtblCategory.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblCategory = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÝ LOẠI SẢN PHẨM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 26, -1, -1));

        jtblCategory.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblCategory.setRowHeight(50);
        jtblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblCategory);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 146, 839, 466));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert.png"))); // NOI18N
        jButton1.setText("Thêm Loại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 314, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Mã Loại");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(851, 165, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Tên Loại Sản Phẩm");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 229, -1, 30));

        txtMaLoai.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        getContentPane().add(txtMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 167, 211, -1));

        txtTenLoai.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        getContentPane().add(txtTenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1012, 232, 213, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(866, 314, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1201, 314, -1, -1));
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 251, 37));

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, -1, 37));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblCategoryMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jtblCategory.getModel();
        int row = jtblCategory.getSelectedRow();
        if(row >=0){
            txtMaLoai.setText(String.valueOf(jtblCategory.getValueAt(row, 0)));
            
            txtTenLoai.setText((String) jtblCategory.getValueAt(row, 1) );
           
        }
    }//GEN-LAST:event_jtblCategoryMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          if(txtMaLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn loại sản phẩm cần xóa!");
        }
        else{
            String idcategory = txtMaLoai.getText();
            String name = txtTenLoai.getText();
             
            
            LoaiDAO.updateCategory(idcategory, name);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
             LoadForm(LoaiDAO.layDanhsachLoai());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(txtMaLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn loại sản phẩm cần xóa!");
        }
        else{
            LoaiDAO.deleteCategory(txtMaLoai.getText());
            JOptionPane.showMessageDialog(this, "Đã xóa loại sản phẩm"+txtTenLoai.getText());
            txtMaLoai.setText("");
           
            txtTenLoai.setText("");
              LoadForm(LoaiDAO.layDanhsachLoai());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          if(txtMaLoai.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn loại sản phẩm cần xóa!");
        }
        else{
            String idcategory = txtMaLoai.getText();
            String name = txtTenLoai.getText();
             
            
            LoaiDAO.insertCategory( name);
            JOptionPane.showMessageDialog(this, "Thêm loại sản phẩm thành công!");
               LoadForm(LoaiDAO.layDanhsachLoai());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
           String searchText = txtSearch.getText();
        LoadForm(LoaiDAO.findCategory(searchText));
    }//GEN-LAST:event_btnSearchActionPerformed

    
     public void LoadForm(ArrayList<Loai> dsLoai){
//        LoaiDAO category = new LoaiDAO();
        
//        dsLoai = LoaiDAO.layDanhsachLoai();
        DefaultTableModel defaultTableModel = (DefaultTableModel) this.jtblCategory.getModel();
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        defaultTableModel.addColumn("Mã Loai ");
        defaultTableModel.addColumn("Tên Loại Sản Phẩm ");
      
     
        for(Loai nv : dsLoai){
            Vector vec = new Vector();
              vec.add(nv.getIdcategory());
            vec.add(nv.getName());
          
            defaultTableModel.addRow(vec);
        }
//        TableColumnModel columnModel = jtblCategory.getColumnModel();
//        columnModel.getColumn(1).setPreferredWidth(150); // Độ rộng cho cột "Name"
//        columnModel.getColumn(2).setPreferredWidth(150);  // Độ rộng cho cột "Age"
//        columnModel.getColumn(4).setPreferredWidth(100); 
//        JTableHeader header = jtblCategory.getTableHeader();
//        header.setFont(new Font("Arial", Font.BOLD, 16)); // Font Arial, đậm, kích cỡ 14
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblCategory;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
