/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.NhanVienDAO;
import DAO.SanPhamDAO;
import POJO.NhanVien;
import POJO.SanPham;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Admin
 */
public class frmProduct extends javax.swing.JInternalFrame {
ArrayList<SanPham> dsSanPham = SanPhamDAO.layDanhsachSanPham();
    /**
     * Creates new form frmProduct
     */
    public frmProduct() {
        initComponents();
        LoadForm(dsSanPham);
        JTableHeader header = jtblProduct.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16)); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProduct = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtHSD = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtMaLoai = new javax.swing.JTextField();
        txtMaNCC = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1334, 729));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("QUẢN LÝ SẢN PHẨM ");
        jLabel1.setMaximumSize(new java.awt.Dimension(1334, 729));
        jLabel1.setMinimumSize(new java.awt.Dimension(1334, 729));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 0, -1, -1));

        jtblProduct.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jtblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblProduct.setRowHeight(50);
        jtblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProduct);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 830, 377));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/insert.png"))); // NOI18N
        jButton1.setText("Thêm Sản Phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 519, -1, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("Tên Sản Phẩm");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Giá");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 192, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Hạn sử dụng");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 258, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel5.setText("Số Lượng");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 325, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel6.setText("Mã Loại");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel7.setText("Mã nhà cung cấp");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 443, -1, -1));

        txtTen.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 152, 180, -1));

        txtGia.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 194, 180, -1));

        txtHSD.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtHSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 260, 180, -1));

        txtSoLuong.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 327, 180, -1));

        txtMaLoai.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 390, 180, -1));

        txtMaNCC.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtMaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 445, 180, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 519, -1, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 520, -1, 40));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel8.setText("Mã Sản Phẩm");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(974, 95, -1, -1));

        txtMaSP.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        getContentPane().add(txtMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 95, 180, -1));

        txtSearch.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 170, 39));

        btnSearch.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProductMouseClicked
        // TODO add your handling code here:
//         DefaultTableModel model = (DefaultTableModel) jtblProduct.getModel();
        int row = jtblProduct.getSelectedRow();
        if(row >=0){
            txtMaSP.setText(String.valueOf(jtblProduct.getValueAt(row, 0)));
            
            txtTen.setText((String) jtblProduct.getValueAt(row, 1) );
             txtGia.setText(String.valueOf(jtblProduct.getValueAt(row, 2)));
           txtHSD.setText(String.valueOf(jtblProduct.getValueAt(row, 3)));
//            txtHSD.setText((String) jtblProduct.getValueAt(row, 3) );
            txtSoLuong.setText(String.valueOf(jtblProduct.getValueAt(row, 4)));
            txtMaLoai.setText(String.valueOf(jtblProduct.getValueAt(row, 5)));
            txtMaNCC.setText(String.valueOf(jtblProduct.getValueAt(row, 6)));
           
           
        }
    }//GEN-LAST:event_jtblProductMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           if(txtMaSP.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm cần xóa!");
        }
        else{
            String idproduct = txtMaSP.getText();
            String name = txtTen.getText();
              String price= txtGia.getText();
            String dateproduct= txtHSD.getText();
            String quantity= txtSoLuong.getText();
            String idcategory= txtMaLoai.getText();
            String idsupplier= txtMaNCC.getText();
            
            SanPhamDAO.updateProduct(idproduct, name, price, dateproduct, quantity, idcategory, idsupplier);
            LoadForm(SanPhamDAO.layDanhsachSanPham());
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(txtMaSP.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm cần xóa!");
        }
        else{
            SanPhamDAO.deleteProduct(txtMaSP.getText());
            JOptionPane.showMessageDialog(this, "Đã xóa sản phẩm"+txtTen.getText());
            txtMaSP.setText("");
            txtTen.setText("");
            txtGia.setText("");
            txtHSD.setText("");
            txtSoLuong.setText("");
            txtMaLoai.setText("");
            txtMaNCC.setText("");
             LoadForm(SanPhamDAO.layDanhsachSanPham());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           if(txtMaSP.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm cần xóa!");
        }
        else{
            String idproduct = txtMaSP.getText();
            String name = txtTen.getText();
              String price= txtGia.getText();
            String dateproduct= txtHSD.getText();
            String quantity= txtSoLuong.getText();
            String idcategory= txtMaLoai.getText();
            String idsupplier= txtMaNCC.getText();
            
            SanPhamDAO.insertProduct(name, price, dateproduct, quantity, idcategory, idsupplier);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
             LoadForm(SanPhamDAO.layDanhsachSanPham());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
            String searchText = txtSearch.getText();
        LoadForm(SanPhamDAO.findProduct(searchText));
    }//GEN-LAST:event_btnSearchActionPerformed

      public void LoadForm(ArrayList<SanPham> dsSanPham){
//        SanPhamDAO product = new SanPhamDAO();
//        ArrayList<SanPham> dsSanPham = new ArrayList<>();
//        dsSanPham = SanPhamDAO.layDanhsachSanPham();
        DefaultTableModel defaultTableModel = (DefaultTableModel) this.jtblProduct.getModel();
        defaultTableModel.setColumnCount(0);
        defaultTableModel.setRowCount(0);
        defaultTableModel.addColumn("Mã sản phẩm ");
        defaultTableModel.addColumn("Tên sản phẩm ");
        defaultTableModel.addColumn("Giá");
        defaultTableModel.addColumn("Hạn sử dụng");
        defaultTableModel.addColumn("Số Lượng");
        defaultTableModel.addColumn("Mã Loại");
        defaultTableModel.addColumn("Mã nhà cung cấp");
     
        for(SanPham nv : dsSanPham){
            Vector vec = new Vector();
              vec.add(nv.getIdproduct());
            vec.add(nv.getName());
            vec.add(nv.getPrice());
            vec.add(nv.getDateproduct());
            vec.add(nv.getQuantity());
            vec.add(nv.getIdcategory());
            vec.add(nv.getIdsupplier());
            defaultTableModel.addRow(vec);
        }
        TableColumnModel columnModel = jtblProduct.getColumnModel();
        columnModel.getColumn(1).setPreferredWidth(150); // Độ rộng cho cột "Name"
        columnModel.getColumn(2).setPreferredWidth(150);  // Độ rộng cho cột "Age"
        columnModel.getColumn(4).setPreferredWidth(100); 
        JTableHeader header = jtblProduct.getTableHeader();
        header.setFont(new Font("Arial", Font.BOLD, 16)); // Font Arial, đậm, kích cỡ 14
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblProduct;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHSD;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables

   
}
